export const POSSIBLE_STATES = [
  "TICKET_CREATED",
  "PACKAGE_RECEIVED",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
  "CANCELLED",
  "NOT_YET_SHIPPED",
  "AVAILABLE_FOR_PICKUP",
  "WAITING_FOR_CUSTOMER_ACTION",
  "IN_TRANSIT",
  "DELIVERY_FAILED",
  "DELIVERED_TO_SENDER",
] as const;
